version: '3.9'

services:
  golang:
    image: golang:latest
    container_name: go_dev
    ports:
      - "3333:3333"
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - db
    command: tail -f /dev/null
      
  db:
    image: postgres:latest
    container_name: postgres_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
      - DB_NAMESPACE=auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db

volumes:
  postgres_data:

networks:
  db: