version: '3.9'

services:
  app:
    tty: true
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "3333:3333"
    environment:
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=appdb
      - MIGRATE_VERSION=v4.18.1
    depends_on:
      - db
    networks:
      - db
      
  db:
    image: postgres:latest
    container_name: postgres_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
      - DB_NAMESPACE=auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db

volumes:
  postgres_data:

networks:
  db: