services:
  golang:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: golang
    networks:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_TIMEZONE=${DB_TIMEZONE}
      - PORT=${PORT}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./app:/app
      - ./objects:/app/objects
      - ./uploads:/app/uploads
    restart: always

volumes:
  postgres_data:
  pgadmin:

networks:
  db:
